//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccidentMember
    {
        public int id { get; set; }
        public int idAccident { get; set; }
        public int idDriver { get; set; }
        public int idAuto { get; set; }
        public string Criminal { get; set; }
    
        public virtual Accident Accident { get; set; }
        public virtual Auto Auto { get; set; }
        public virtual Driver Driver { get; set; }
    }
}
