//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accident
    {
        public Accident()
        {
            this.AccidentMember = new HashSet<AccidentMember>();
        }
    
        public int id { get; set; }
        public int idStreet { get; set; }
        public int idWorker { get; set; }
        public string Place { get; set; }
        public string Description { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Street Street { get; set; }
        public virtual Worker Worker { get; set; }
        public virtual ICollection<AccidentMember> AccidentMember { get; set; }
    }
}
