//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auto
    {
        public Auto()
        {
            this.Accounting = new HashSet<Accounting>();
            this.Illegal = new HashSet<Illegal>();
        }
    
        public int id { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public System.DateTime Year { get; set; }
        public string VinNumber { get; set; }
    
        public virtual ICollection<Accounting> Accounting { get; set; }
        public virtual ICollection<Illegal> Illegal { get; set; }
    }
}
