//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class District
    {
        public District()
        {
            this.DutyDots = new HashSet<DutyDots>();
            this.Street = new HashSet<Street>();
        }
    
        public int id { get; set; }
        public string District1 { get; set; }
    
        public virtual ICollection<DutyDots> DutyDots { get; set; }
        public virtual ICollection<Street> Street { get; set; }
    }
}
