//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class DutyDots
    {
        public DutyDots()
        {
            this.Duty = new HashSet<Duty>();
        }
    
        public int id { get; set; }
        public int idDutyDotsType { get; set; }
        public int idDistrict { get; set; }
        public string FirstPlace { get; set; }
        public string LastPlace { get; set; }
    
        public virtual District District { get; set; }
        public virtual ICollection<Duty> Duty { get; set; }
        public virtual DutyDotsType DutyDotsType { get; set; }
    }
}
