//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duty
    {
        public Duty()
        {
            this.Illegal = new HashSet<Illegal>();
        }
    
        public int id { get; set; }
        public int idWorker { get; set; }
        public System.DateTime Date { get; set; }
        public string Place { get; set; }
    
        public virtual ICollection<Illegal> Illegal { get; set; }

        public Worker DutyWorker
        {
            get
            {
                return Repositories.GetWorkerById(idWorker);
            }
        }

        
    }
}
