//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int id { get; set; }
        public int idWorker { get; set; }
        public int idRank { get; set; }
        public int idPosition { get; set; }
        public System.DateTime Date { get; set; }
    
        public virtual Position Position { get; set; }
        public virtual Rank Rank { get; set; }
        public virtual Worker Worker { get; set; }
    }
}
