//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    //using Microsoft.EntityFrameworkCore;
    //using Microsoft.EntityFrameworkCore;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class gaiEngEntities : DbContext
    {
        public gaiEngEntities()
            : base("name=gaiEngEntities")
        {
        }
        
        /*public gaiEngEntities(DbContextOptions<gaiEngEntities> options) : base(options)
        {

        }
        */

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        public DbSet<Accounting> Accounting { get; set; }
        public DbSet<Auto> Auto { get; set; }
        public DbSet<Driver> Driver { get; set; }
        public DbSet<Duty> Duty { get; set; }
        public DbSet<Illegal> Illegal { get; set; }
        public DbSet<IllegalType> IllegalType { get; set; }
        public DbSet<Rank> Rank { get; set; }
        public DbSet<User> User { get; set; }
        public DbSet<Worker> Worker { get; set; }
    }
}
