//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rank
    {
        public Rank()
        {
            this.Worker = new HashSet<Worker>();
        }
    
        public int id { get; set; }
        public string Rank1 { get; set; }
    
        public virtual Rank Rank11 { get; set; }
        public virtual Rank Rank2 { get; set; }
        public virtual ICollection<Worker> Worker { get; set; }

        /*public Rank RankWorker
        {
            get
            {
                return Repositories.GetRankById(id);
            }
        }*/

        /*public List<User> PositionUsers
        {
            get
            {
                return DataWorker.GetAllUsersByPositionId(Id);
            }
        }*/
        public List<Worker> WorkerRank
        {
            get
            {
                return Repositories.GetAllWorkersByRankId(id);
            }
        }
    }
}
