//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Street
    {
        public Street()
        {
            this.Accident = new HashSet<Accident>();
        }
    
        public int id { get; set; }
        public int idDistrict { get; set; }
        public string Street1 { get; set; }
    
        public virtual ICollection<Accident> Accident { get; set; }
        public virtual District District { get; set; }
    }
}
