//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypesOfIAP
    {
        public int id { get; set; }
        public string Type { get; set; }
        public string Encouraging { get; set; }
    
        public virtual IAP IAP { get; set; }
    }
}
