//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using gaiEntiry.Repositories;
    using gaiEntiry.ViewsModel;
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Accounting = new HashSet<Accounting>();
        }
    
        public int id { get; set; }
        public int idRank { get; set; }
        public string LastName { get; set; }
        public string FirsName { get; set; }
        public string Surname { get; set; }
    
        public virtual ICollection<Accounting> Accounting { get; set; }
        public virtual Rank Rank { get; set; }
        public Rank WorkerRank
        {
            get
            {
                return RankRepositories.GetRankById(idRank);
            }
        }

        public List<Duty> WorkerDuty
        {
            get
            {
                return DutyRepositories.GetAllDutiesByWorkerId(id);
            }
        }

        public List<Accounting> WorkerAccounting
        {
            get
            {
                return AccountingRepositories.GetAllAccountingsByWorkerId(id);
            }
        }

        
    }
}
