//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gaiEntiry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public Worker()
        {
            this.Accident = new HashSet<Accident>();
            this.Accounting = new HashSet<Accounting>();
            this.Duty = new HashSet<Duty>();
            this.History = new HashSet<History>();
            this.IAP = new HashSet<IAP>();
        }
    
        public int id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Surname { get; set; }
        public System.DateTime Birth { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Accident> Accident { get; set; }
        public virtual ICollection<Accounting> Accounting { get; set; }
        public virtual ICollection<Duty> Duty { get; set; }
        public virtual ICollection<History> History { get; set; }
        public virtual ICollection<IAP> IAP { get; set; }
    }
}
